function [r,dr] = rFileIRK4(in1,xk,dt)
%rFileIRK4
%    [R,DR] = rFileIRK4(IN1,XK,DT)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    16-Oct-2022 21:48:20

K1 = in1(1,:);
K2 = in1(2,:);
t2 = xk.*2.0;
t4 = dt./2.0;
t3 = -t2;
r = [-K1+t3-dt.*(K1./4.0-K2.*3.867513459481287e-2).*2.0;-K2+t3-dt.*(K1.*5.386751345948129e-1+K2./4.0).*2.0];
if nargout > 1
    t5 = -t4;
    t6 = t5-1.0;
    dr = reshape([t6,dt.*(-1.077350269189626),dt.*7.735026918962573e-2,t6],[2,2]);
end
