function f2 = VanDerPol(tODE45_tight,in2)
%VanDerPol
%    F2 = VanDerPol(tODE45_tight,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    15-Oct-2022 17:20:04

x1 = in2(1,:);
x2 = in2(2,:);
f2 = [x2;-x1-x2.*(x1.^2.*5.0-5.0)];
