function f = func_VanDerPol_implicit(in1)
%func_VanDerPol_implicit
%    F = func_VanDerPol_implicit(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    17-Oct-2022 12:48:26

x1 = in1(1,:);
x2 = in1(2,:);
f = [x2;-x1-x2.*(x1.^2.*5.0-5.0)];
