function [r,dr] = rFileIEuler(t,in2,in3,dt)
%rFileIEuler
%    [R,DR] = rFileIEuler(T,IN2,IN3,DT)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    17-Oct-2022 09:38:11

x1 = in2(1,:);
x2 = in2(2,:);
xNext1 = in3(1,:);
xNext2 = in3(2,:);
t2 = xNext1.^2;
t3 = t2.*5.0;
t4 = t3-5.0;
r = [x1-xNext1+dt.*xNext2;x2-xNext2-dt.*(xNext1+t4.*xNext2)];
if nargout > 1
    dr = reshape([-1.0,-dt.*(xNext1.*xNext2.*1.0e+1+1.0),dt,-dt.*t4-1.0],[2,2]);
end
