function [r,dr] = rFileIRK4(in1,xk,dt)
%rFileIRK4
%    [R,DR] = rFileIRK4(IN1,XK,DT)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    21-Oct-2022 10:09:47

K1 = in1(1,:);
K2 = in1(2,:);
t2 = xk.*1.45e+2;
t4 = dt.*(1.45e+2./4.0);
t3 = -t2;
r = [-K1+t3-dt.*(K1./4.0-K2.*3.867513459481287e-2).*1.45e+2;-K2+t3-dt.*(K1.*5.386751345948129e-1+K2./4.0).*1.45e+2];
if nargout > 1
    t5 = -t4;
    t6 = t5-1.0;
    dr = reshape([t6,dt.*(-7.810789451624787e+1),dt.*5.607894516247866,t6],[2,2]);
end
